# Работа с БД

In [ ]:
import os
import pandas as pd
from sqlalchemy import create_engine
from catboost import CatBoostClassifier
from dotenv import load_dotenv

load_dotenv()

DB_CONN = os.getenv("DB_URL", "postgresql://username:password@host:port/database_name")

TABLE_USERS = os.getenv("TABLE_USERS", "public.user_data")
TABLE_POSTS = os.getenv("TABLE_POSTS", "public.post_text_df")
TABLE_FEED = os.getenv("TABLE_FEED", "public.feed_data")
TABLE_LIKES_SAVE = os.getenv("TABLE_LIKES_SAVE", "my_likes_table")
TABLE_USERS_SAVE = os.getenv("TABLE_USERS_SAVE", "my_users_table")
TABLE_POSTS_SAVE = os.getenv("TABLE_POSTS_SAVE", "my_posts_table")
TABLE_SCORE_SAVE = os.getenv("TABLE_SCORE_SAVE", "my_score_table")

engine = create_engine(DB_CONN)

In [1]:
user = pd.read_sql(f'SELECT * FROM {TABLE_USERS}', con=engine)
post = pd.read_sql(f'SELECT * FROM {TABLE_POSTS}', con=engine)
feed = pd.read_sql(f'SELECT * FROM {TABLE_FEED} LIMIT 2000000', con=engine)

# Реализация Item-based подхода

In [3]:
likes = feed[feed['action']=='like'].copy()
likes = likes.sort_values('timestamp')
likes

                  timestamp  user_id  post_id action  target
861513  2021-10-01 06:09:21    56905     5381   like       0
1194997 2021-10-01 06:10:27   147495        6   like       0
1686817 2021-10-01 06:10:27   140692     4652   like       0
861515  2021-10-01 06:12:15    56905     4106   like       0
1812688 2021-10-01 06:14:18    96797      967   like       0
...                     ...      ...      ...    ...     ...
1982372 2021-12-29 23:38:25    57183     4139   like       0
277570  2021-12-29 23:38:25   126794     5364   like       0
277574  2021-12-29 23:46:10   126794      565   like       0
1982376 2021-12-29 23:46:10    57183      610   like       0
386810  2021-12-29 23:46:10   140395     4485   like       0

[212281 rows x 5 columns]

In [4]:
user_likes = likes.groupby('user_id')['post_id'].apply(list)
user_likes

user_id
49517     [4136, 1559, 1385, 6472, 3175, 5570, 1053, 182...
49518     [2989, 5424, 5049, 1807, 1427, 1008, 6258, 267...
49519     [4096, 1912, 4366, 1542, 7214, 1737, 5457, 595...
49520     [860, 1626, 3037, 400, 334, 426, 2619, 5278, 7...
49521     [3425, 2893, 1554, 1559, 4214, 6255, 63, 2433,...
                                ...
160055    [6295, 7296, 1323, 543, 1814, 6467, 1917, 1175...
160056    [779, 1522, 1349, 5040, 482, 1446, 653, 44, 41...
160057    [2527, 835, 403, 686, 5525, 2527, 2872, 3700, ...
160058    [6023, 6938, 3546, 5002, 3262, 5223, 3052, 434...
160059    [6535, 252, 3608, 3959, 4431, 7042, 6776, 826,...
Name: post_id, Length: 4239, dtype: object

In [6]:
from collections import Counter
pair_count = Counter()
for likes_list in user_likes:
  recent_likes = likes_list[-10:]
  for i in range(len(recent_likes)):
    for j in range(i+1, len(recent_likes)):
      pair_count[(recent_likes[i], recent_likes[j])] +=1
      pair_count[(recent_likes[j], recent_likes[i])] +=1

item_item_sim = {}
for (post_a, post_b), count in pair_count.items():
  if post_a not in item_item_sim:
    item_item_sim[post_a] = {}
  item_item_sim[post_a][post_b] = count

item_item_sim

# Обработка датасета

In [8]:
df = feed.merge(user, on='user_id', how='left')
df = df.merge(post, on='post_id', how='left')

df

,timestamp,user_id,post_id,action,target,gender,age,country,city,exp_group,os,source,text,topic
0,2021-12-12 22:22:45,133662,1128,view,0,1,21,Russia,Verkhniy Tagil,3,iOS,organic,Top Tories on Lib Dem hit list\n\nThe Liberal ...,politics
1,2021-12-12 22:25:15,133662,1428,view,0,1,21,Russia,Verkhniy Tagil,3,iOS,organic,Umaga ready for Lions\n\nAll Blacks captain Ta...,sport
2,2021-12-12 22:25:29,133662,1527,view,0,1,21,Russia,Verkhniy Tagil,3,iOS,organic,Player burn-out worries Robinson\n\nEngland co...,sport
3,2021-12-12 22:27:28,133662,2556,view,0,1,21,Russia,Verkhniy Tagil,3,iOS,organic,"Cases will wax and wane, but #coronavirus is n...",covid
4,2021-12-12 22:29:19,133662,4374,view,0,1,21,Russia,Verkhniy Tagil,3,iOS,organic,This TVM seems to have polarised opinions amon...,movie
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,2021-12-15 16:13:39,153373,5336,view,0,1,16,Russia,Saint Petersburg,0,iOS,organic,By far the most important requirement for any ...,movie
1999996,2021-12-15 16:16:37,153373,5017,view,0,1,16,Russia,Saint Petersburg,0,iOS,organic,Lets just say that it might be the worst movie...,movie
1999997,2021-12-15 16:17:12,153373,5123,view,1,1,16,Russia,Saint Petersburg,0,iOS,organic,I own this movie. And it is terribly hard to f...,movie
1999998,2021-12-15 16:19:37,153373,5123,like,0,1,16,Russia,Saint Petersburg,0,iOS,organic,I own this movie. And it is terribly hard to f...,movie
1999999,2021-12-15 16:19:39,153373,264,view,0,1,16,Russia,Saint Petersburg,0,iOS,organic,Khodorkovsky ally denies charges\n\nA close as...,business

In [9]:
df = df[df['action'] == 'view']
df = df.drop('action', axis = 1)

df = df.drop('text', axis = 1)
df = df.drop('source', axis=1)

In [10]:
user_likes_dict = user_likes.to_dict()

def get_item_based_score(user_id, target_post_id):
  if user_id not in user_likes_dict or target_post_id not in item_item_sim:
    return 0

  past_likes = user_likes_dict[user_id]
  score = 0
  sim_posts = item_item_sim[target_post_id]

  for past_post in past_likes:
    if past_post in sim_posts:
      score += sim_posts[past_post]

  return score

In [11]:
df['item_similarity_score'] = df.apply(
    lambda x:get_item_based_score(x['user_id'], x['post_id']), axis = 1
    )

In [12]:
df['month'] = df['timestamp'].dt.month
df['hour'] = df['timestamp'].dt.hour

df = df.sort_values('timestamp')
df = df.drop('timestamp', axis =1)

df = df.drop(['user_id', 'post_id'], axis = 1)
df

In [15]:
board = int(df.shape[0]*0.8)
train = df.iloc[:board].copy()
test = df.iloc[board:].copy()

train_X = train.drop('target', axis = 1)
train_y = train['target']

test_X = test.drop('target', axis = 1)
test_y = test['target']

# Обучение CatBoost

In [23]:
def load_models():
    model = CatBoostClassifier()
    model_path = '/content/catboost_model_5'

    model.load_model(model_path)

    return model

In [18]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.8)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.2)

In [19]:
from catboost import CatBoostClassifier

In [31]:
train_columns = [
    'gender', 'age', 'country', 'city', 'exp_group', 'os',
    'topic', 'item_similarity_score', 'month', 'hour'
]

test_X_sorted = test_X[train_columns].copy()

model = load_models()
val_df = test_X.copy()
val_df['target'] = test_y.copy()
val_df['user_id'] = df['user_id']

val_df['predict_proba'] = model.predict_proba(test_X_sorted)[:, 1]
val_df.sort_values(['user_id', 'predict_proba'], ascending=[True, False], inplace=True)

top_5_recs = val_df.groupby('user_id').head(5)

hit_rate = top_5_recs.groupby('user_id')['target'].max().mean()

print(f"HitRate@5: {hit_rate:.4f}")

HitRate@5: 0.9868

In [34]:
cat_cols = df.select_dtypes(include = object).columns
cat_cols

Index(['country', 'city', 'os', 'topic'], dtype='object')

In [35]:
model = CatBoostClassifier(
    cat_features = cat_cols.tolist(),
    eval_metric='AUC',
    verbose = 100
)

model.fit(train_X, train_y)

Learning rate set to 0.229258
0:	total: 2.06s	remaining: 34m 16s
100:	total: 2m 32s	remaining: 22m 39s
200:	total: 5m 4s	remaining: 20m 11s
300:	total: 7m 36s	remaining: 17m 39s
400:	total: 10m 10s	remaining: 15m 11s
500:	total: 12m 41s	remaining: 12m 38s
600:	total: 15m 17s	remaining: 10m 9s
700:	total: 17m 48s	remaining: 7m 35s
800:	total: 20m 21s	remaining: 5m 3s
900:	total: 22m 57s	remaining: 2m 31s
999:	total: 25m 33s	remaining: 0us

In [36]:
from sklearn.metrics import roc_auc_score

preds = model.predict_proba(test_X)[:, 1]

auc = roc_auc_score(test_y, preds)

model.save_model('catboost_model_5', format = 'cbm')

In [38]:
auc = roc_auc_score(test_y, preds)
auc

np.float64(0.9060331747715176)

# Выгрузка артефактов

In [ ]:
user_table = pd.read_sql(f'SELECT * FROM {TABLE_USERS}', con=engine)
user_table.to_sql(f'{TABLE_USERS_SAVE}', con=engine)

205

In [ ]:
post_table = pd.read_sql(f'SELECT * FROM {TABLE_POSTS}', con=engine)
post_table.to_sql(f'{TABLE_POSTS_SAVE}', con=engine)

23

In [32]:
score_data = []
for post_id, neigh in item_item_sim.items():
  for neigh_id, score in neigh.items():
    score_data.append({'post_id': post_id, 'neighbor_id': neigh_id, 'score': score})

score_df = pd.DataFrame(score_data)
score_df.to_sql(f'{TABLE_SCORE_SAVE}', con=engine)

815

In [2]:
likes_df = pd.read_sql(f"SELECT user_id, post_id FROM {TABLE_FEED} WHERE action='like' LIMIT 2000000", con=engine)
likes_df.to_sql(
    f'{TABLE_LIKES_SAVE}',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=5000,
    method='multi'
)

2000000