# Работа с БД

In [ ]:
import os
import pandas as pd
from sqlalchemy import create_engine
# from catboost import CatBoostClassifier
from dotenv import load_dotenv

load_dotenv()

DB_CONN = os.getenv("DB_URL", "postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml")

TABLE_USERS = os.getenv("TABLE_USERS", "public.user_data")
TABLE_POSTS = os.getenv("TABLE_POSTS", "public.post_text_df")
TABLE_FEED = os.getenv("TABLE_FEED", "public.feed_data")
TABLE_LIKES_SAVE = os.getenv("TABLE_LIKES_SAVE", "valeriya_nikitina_likes_lesson_22")
TABLE_USERS_SAVE = os.getenv("TABLE_USERS_SAVE", "valeriya_nikitina_lesson_22")
TABLE_POSTS_SAVE = os.getenv("TABLE_POSTS_SAVE", "valeriya_nikitina_posts_lesson_22")
TABLE_SCORE_SAVE = os.getenv("TABLE_SCORE_SAVE", "valeriya_nikitina_score_lesson_22")

engine = create_engine(DB_CONN)

In [ ]:
user = pd.read_sql(f'SELECT * FROM {TABLE_USERS}', con=engine)
post = pd.read_sql(f'SELECT * FROM {TABLE_POSTS}', con=engine)
feed = pd.read_sql(f'SELECT * FROM {TABLE_FEED} LIMIT 2000000', con=engine)

# Реализация Item-based подхода

In [ ]:
likes = feed[feed['action']=='like'].copy()
likes = likes.sort_values('timestamp')
likes

                  timestamp  user_id  post_id action  target
1791986 2021-10-01 06:07:41    67155     4695   like       0
1659488 2021-10-01 06:08:34   111119     5590   like       0
1053891 2021-10-01 06:09:43    81304     4884   like       0
997921  2021-10-01 06:09:43    74454     5566   like       0
1988068 2021-10-01 06:09:43    16470     4067   like       0
...                     ...      ...      ...    ...     ...
1012199 2021-12-29 23:36:59   111030     1187   like       0
1939492 2021-12-29 23:39:33   151837     5078   like       0
1012202 2021-12-29 23:39:33   111030     1788   like       0
1939494 2021-12-29 23:41:16   151837     4152   like       0
1012204 2021-12-29 23:41:16   111030     4954   like       0

[214793 rows x 5 columns]

In [ ]:
user_likes = likes.groupby('user_id')['post_id'].apply(list)
user_likes

user_id
9404      [3634, 5268, 3017, 6458, 3540, 5648, 5794, 168...
9405      [3959, 4889, 6595, 5948, 1112, 3425, 1231, 172...
9406      [4980, 2845, 1173, 557, 5398, 6048, 7059, 1194...
9407      [1924, 93, 5390, 3943, 5580, 1721, 1666, 2606,...
9408      [6760, 3523, 1280, 5914, 1106, 1494, 4272, 714...
                                ...
164921    [1744, 1556, 1496, 744, 1101, 1552, 6989, 6004...
164922    [1935, 5940, 2492, 1626, 1377, 642, 1904, 2935...
164923    [4634, 4906, 2819, 1798, 5114, 4730, 6289, 690...
164924    [70, 6391, 2631, 1593, 1213, 3671, 2525, 6161,...
164925    [4352, 2615, 6445, 7121, 1579, 1776, 2838, 210...
Name: post_id, Length: 4200, dtype: object

In [ ]:
from collections import Counter
pair_count = Counter()
for likes_list in user_likes:
  recent_likes = likes_list[-10:]
  for i in range(len(recent_likes)):
    for j in range(i+1, len(recent_likes)):
      pair_count[(recent_likes[i], recent_likes[j])] +=1
      pair_count[(recent_likes[j], recent_likes[i])] +=1

item_item_sim = {}
for (post_a, post_b), count in pair_count.items():
  if post_a not in item_item_sim:
    item_item_sim[post_a] = {}
  item_item_sim[post_a][post_b] = count

item_item_sim

{6458: {3540: 1,
  5648: 1,
  5794: 1,
  1689: 1,
  1212: 1,
  5058: 1,
  1304: 1,
  6945: 1,
  1635: 1,
  2873: 1,
  6482: 1,
  5425: 1,
  1086: 1,
  939: 1,
  1368: 1,
  1686: 1,
  5614: 1,
  6193: 1,
  6910: 1,
  1396: 1,
  6772: 1,
  2555: 1,
  1191: 1,
  1920: 1,
  1265: 1,
  3494: 1,
  4958: 1,
  1391: 1,
  1670: 1,
  5640: 1,
  2029: 1,
  6285: 1,
  6988: 1,
  5123: 1,
  2146: 1,
  442: 1,
  2321: 1,
  1867: 1,
  1755: 1,
  546: 1,
  2173: 1,
  517: 1,
  5199: 1,
  4742: 1,
  3214: 1,
  1300: 1,
  4680: 1,
  7082: 1,
  1240: 1,
  4724: 1,
  818: 1,
  6535: 1,
  1571: 1,
  3358: 1,
  3072: 2,
  1800: 1,
  3366: 1,
  1403: 1,
  3825: 1,
  7014: 1,
  6517: 1,
  3756: 1},
 3540: {6458: 1,
  5648: 1,
  5794: 1,
  1689: 1,
  1212: 1,
  5058: 2,
  1304: 1,
  6945: 1,
  1635: 1,
  1371: 1,
  5887: 1,
  1718: 1,
  3869: 2,
  7132: 1,
  5283: 1,
  4279: 1,
  5338: 1,
  594: 1,
  5392: 1,
  4979: 1,
  1935: 1,
  6597: 1,
  6777: 1,
  5944: 1,
  1538: 1,
  6295: 1,
  3080: 1,
  6976: 1,
  5272: 1,
  942: 1,
  1587: 1,
  4431: 1,
  1484: 1,
  1107: 1,
  2895: 1,
  5247: 1,
  3226: 1,
  1400: 1,
  931: 1,
  2360: 1,
  3268: 1,
  6405: 1,
  3808: 1,
  5323: 1,
  1650: 1,
  7064: 1,
  6644: 1,
  1895: 1,
  3414: 1,
  6942: 1,
  1453: 1,
  1794: 1,
  1380: 1,
  1386: 1,
  7042: 1,
  5798: 1,
  2896: 1,
  7287: 1,
  1175: 1,
  7046: 1,
  6864: 1,
  3394: 1,
  680: 1,
  1389: 1,
  5924: 1,
  3607: 1,
  7296: 1,
  1435: 1,
  1855: 1,
  2997: 1,
  994: 1,
  1688: 1,
  173: 1,
  4294: 1,
  7121: 1,
  5730: 1,
  1661: 1,
  358: 1,
  556: 1,
  2211: 1,
  3616: 1,
  1153: 1,
  4093: 1,
  2780: 1,
  5187: 1,
  4744: 1,
  1502: 1,
  760: 1,
  3952: 1,
  2215: 1,
  5753: 1,
  3756: 1,
  5739: 1,
  2601: 1,
  3897: 1,
  6157: 1,
  134: 1,
  984: 1,
  3205: 1,
  4049: 1,
  790: 1,
  5723: 1},
 5648: {6458: 1,
  3540: 1,
  5794: 1,
  1689: 1,
  1212: 1,
  5058: 1,
  1304: 1,
  6945: 1,
  1635: 1,
  1788: 1,
  3840: 1,
  6190: 1,
  4671: 1,
  1719: 1,
  4783: 1,
  1598: 1,
  2858: 1,
  5735: 1,
  1068: 1,
  3324: 1,
  3030: 1,
  6266: 1,
  5973: 1,
  3714: 1,
  6753: 1,
  4370: 1,
  6777: 1,
  6285: 1,
  3804: 1,
  1556: 1,
  4764: 1,
  1753: 1,
  1727: 1,
  1767: 1,
  3142: 1,
  3695: 1,
  6192: 1,
  1859: 1,
  4759: 1,
  2349: 1,
  2239: 1,
  921: 1,
  5126: 1,
  6446: 1,
  182: 1,
  124: 1,
  5137: 1,
  3587: 1,
  1219: 1,
  1243: 1,
  5590: 1,
  1144: 1,
  1003: 1,
  1322: 1,
  4721: 1,
  3499: 1,
  5359: 1,
  2508: 1,
  218: 1,
  4712: 1,
  975: 1,
  1707: 2,
  5576: 1,
  6644: 1,
  6935: 1,
  6218: 1,
  1664: 1,
  4552: 1,
  5239: 1,
  6282: 1,
  2281: 1,
  3550: 1,
  7060: 1,
  1681: 1,
  2975: 1,
  2227: 1,
  5739: 1,
  1818: 1,
  5798: 1,
  4927: 1,
  5127: 1,
  135: 1,
  5062: 1,
  5072: 1,
  5696: 1,
  2345: 1,
  682: 1,
  3588: 1,
  1299: 1},
 5794: {6458: 1,
  3540: 1,
  5648: 1,
  1689: 1,
  1212: 1,
  5058: 1,
  1304: 1,
  6945: 1,
  1635: 2,
  6897: 1,
  4763: 1,
  6173: 2,
  1730: 2,
  6310: 1,
  1133: 1,
  463: 1,
  7265: 1,
  2622: 1,
  2469: 1,
  3235: 1,
  3100: 1,
  1189: 1,
  3773: 1,
  1377: 1,
  1777: 1,
  5812: 1,
  1529: 1,
  2607: 1,
  7315: 1,
  4834: 1,
  1790: 1,
  5961: 1,
  3143: 1,
  1832: 1,
  6510: 1,
  63: 1,
  3915: 1,
  1752: 1,
  148: 1,
  1216: 1,
  921: 1,
  928: 1,
  3226: 1,
  834: 1,
  5624: 1,
  6896: 1,
  5737: 1,
  6111: 1,
  6066: 1,
  5622: 1,
  2346: 1,
  1369: 1,
  7311: 1,
  5443: 1,
  1479: 1,
  5203: 1,
  3085: 1,
  5883: 1,
  3269: 1,
  1505: 1,
  1953: 1,
  5689: 1,
  4175: 1,
  1491: 1,
  1382: 1,
  1074: 1,
  6117: 1,
  258: 1,
  565: 1,
  4233: 1,
  5948: 1,
  230: 1,
  4262: 1,
  7238: 1,
  1579: 1,
  1825: 1,
  3374: 1,
  5449: 1,
  96: 1,
  7175: 1,
  3912: 1,
  4359: 1,
  5327: 1,
  1293: 2,
  3309: 1,
  7105: 1,
  10: 1,
  1042: 1,
  1540: 1,
  3907: 1,
  383: 1,
  757: 1,
  6567: 1,
  5314: 1,
  1980: 1,
  1347: 1,
  1138: 1,
  1162: 1,
  1773: 1,
  2380: 1,
  1250: 1,
  946: 1,
  1452: 1,
  1951: 1,
  4187: 1,
  1310: 1,
  4607: 1,
  6939: 1,
  3004: 1,
  6266: 1,
  4843: 1,
  3979: 1,
  560: 1,
  3259: 1,
  5126: 1,
  1155: 1,
  4049: 1,
  6258: 1,
  6597: 1,
  3762: 1,
  1365: 1,
  3029: 1,
  2545: 1,
  1086: 1,
  2477: 1,
  4760: 1,
  2798: 1,
  1097: 1,
  3307: 1,
  1901: 1,
  2956: 1,
  1884: 1,
  2356: 1,
  1211: 1,
  6584: 1,
  7039: 1,
  6076: 1,
  4627: 1,
  1498: 1,
  4062: 1},
 1689: {6458: 1,
  3540: 1,
  5648: 1,
  5794: 1,
  1212: 1,
  5058: 1,
  1304: 1,
  6945: 1,
  1635: 1,
  1906: 1,
  3345: 1,
  1673: 1,
  308: 1,
  6554: 1,
  5186: 1,
  1019: 1,
  3275: 1,
  1207: 1,
  226: 1,
  1809: 1,
  3331: 1,
  1584: 1,
  3147: 1,
  3574: 1,
  1414: 1,
  1631: 1,
  985: 1,
  204: 1,
  4010: 1,
  4941: 1,
  2409: 1,
  6476: 1,
  6752: 1,
  5513: 1,
  1342: 1,
  1995: 1,
  500: 1,
  1311: 1,
  2361: 1,
  1008: 1,
  6482: 1,
  1366: 1,
  5854: 1,
  6070: 1,
  1534: 1,
  7148: 1,
  2845: 1,
  1253: 1,
  1280: 1,
  1150: 1,
  1049: 1,
  5397: 1,
  4971: 1,
  1557: 1,
  1888: 1,
  5878: 1,
  1361: 1,
  1403: 1,
  1283: 1,
  6206: 1,
  940: 1,
  6997: 1,
  7180: 1},
 1212: {6458: 1,
  3540: 1,
  5648: 1,
  5794: 1,
  1689: 1,
  5058: 1,
  1304: 1,
  6945: 1,
  1635: 1,
  1183: 1,
  6276: 1,
  2755: 1,
  1656: 1,
  3145: 1,
  5482: 1,
  2798: 1,
  1754: 1,
  1763: 1,
  4793: 1,
  5924: 1,
  6920: 1,
  4705: 1,
  6283: 1,
  3940: 1,
  2272: 1,
  3212: 1,
  4097: 1,
  7106: 1,
  7134: 1,
  4477: 1,
  7257: 1,
  1479: 1,
  3675: 1,
  3878: 1,
  3024: 1,
  1023: 1,
  1325: 1,
  5252: 1,
  3497: 1,
  146: 1,
  2240: 1,
  6577: 1,
  3861: 1,
  1811: 1,
  6558: 1,
  1935: 1,
  131: 1,
  6253: 1,
  1847: 1,
  5938: 1,
  1798: 1,
  3338: 1,
  2815: 1,
  846: 1,
  1203: 1,
  2138: 1,
  1235: 1,
  6467: 1,
  1571: 1,
  1805: 1,
  3927: 1,
  6606: 1,
  5559: 1,
  1495: 1,
  1795: 1,
  5936: 1,
  3507: 1,
  7141: 1,
  3302: 1,
  3394: 1,
  1140: 1,
  1907: 1},
 5058: {6458: 1,
  3540: 2,
  5648: 1,
  5794: 1,
  1689: 1,
  1212: 1,
  1304: 1,
  6945: 1,
  1635: 1,
  6090: 1,
  5540: 1,
  2965: 1,
  6533: 1,
  3423: 1,
  6218: 1,
  1693: 1,
  1280: 1,
  1051: 1,
  6362: 1,
  93: 1,
  2433: 1,
  6500: 1,
  896: 1,
  1588: 1,
  298: 1,
  898: 1,
  696: 1,
  1010: 1,
  3278: 1,
  1784: 1,
  3654: 1,
  638: 1,
  1048: 1,
  5967: 1,
  2108: 1,
  30: 1,
  4853: 1,
  4233: 1,
  3875: 1,
  979: 1,
  2567: 1,
  5482: 1,
  1335: 1,
  3643: 1,
  3688: 1,
  1847: 1,
  2565: 1,
  1651: 1,
  1399: 1,
  577: 1,
  3470: 1,
  1633: 1,
  1632: 1,
  6298: 1,
  3596: 1,
  5823: 1,
  6151: 1,
  2455: 1,
  3546: 1,
  2644: 1,
  7195: 1,
  2988: 1,
  3298: 1,
  4652: 1,
  1647: 1,
  5419: 1,
  6096: 1,
  6497: 2,
  1729: 1,
  4444: 1,
  6773: 1,
  1059: 1,
  3920: 1,
  4096: 1,
  4910: 1,
  7281: 1,
  5828: 1,
  827: 1,
  4827: 1,
  3966: 1,
  3964: 1,
  5208: 1,
  6702: 1,
  3897: 1,
  6157: 1,
  134: 1,
  984: 1,
  3205: 1,
  4049: 1,
  790: 1,
  5723: 1},
 1304: {6458: 1,
  3540: 1,
  5648: 1,
  5794: 1,
  1689: 1,
  1212: 1,
  5058: 1,
  6945: 1,
  1635: 1,
  1326: 1,
  3805: 1,
  4546: 1,
  4407: 1,
  1734: 1,
  4272: 1,
  5000: 1,
  2709: 1,
  1759: 1,
  1399: 1,
  5355: 1,
  2312: 1,
  986: 1,
  661: 1,
  3613: 1,
  1252: 1,
  1896: 1,
  2630: 1,
  1175: 2,
  3085: 1,
  6572: 1,
  3066: 1,
  4039: 1,
  2685: 1,
  5545: 1,
  523: 1,
  1684: 1,
  1775: 1,
  1883: 1,
  1905: 1,
  1765: 1,
  6476: 1,
  2376: 1,
  1461: 1,
  3226: 2,
  1584: 1,
  7046: 1,
  3410: 1,
  1360: 1,
  6224: 1,
  3466: 1,
  4431: 2,
  3362: 1,
  5270: 1,
  7016: 1,
  1486: 1,
  2641: 1,
  1347: 1,
  1708: 1,
  3047: 1,
  5936: 1,
  4629: 1,
  4632: 1,
  1177: 1,
  2433: 1,
  7177: 1,
  3769: 1,
  7008: 1,
  1730: 1,
  1330: 1,
  3916: 1,
  6513: 1,
  1912: 1,
  1401: 1,
  1655: 1,
  1491: 1,
  3238: 1,
  2892: 1,
  5888: 2,
  6610: 1,
  364: 1,
  3587: 1,
  2192: 1,
  6347: 1,
  5130: 1,
  3394: 1,
  7077: 1,
  4543: 1,
  2700: 1,
  2822: 1,
  4144: 1,
  4889: 1,
  3267: 1,
  5722: 1,
  6991: 1,
  6514: 1,
  4671: 1,
  6967: 2,
  739: 1,
  1798: 1,
  1890: 1,
  2547: 1,
  5938: 1,
  6745: 1,
  5887: 1,
  5515: 2,
  3986: 1,
  5219: 1,
  1715: 1,
  6323: 1,
  4155: 1,
  1118: 1,
  1834: 1,
  196: 1,
  4151: 1,
  2063: 1,
  1797: 1,
  973: 1,
  981: 1,
  2149: 1,
  3396: 1,
  1428: 1,
  1133: 2,
  6346: 1,
  6875: 1,
  324: 1,
  1063: 1,
  1859: 1,
  5077: 1,
  4646: 1,
  1358: 1,
  3566: 1,
  2409: 1,
  2352: 1,
  5027: 1,
  5421: 1,
  3404: 1,
  1542: 1,
  5715: 1,
  5426: 1,
  587: 1,
  6932: 1,
  6497: 1,
  385: 1,
  390: 1,
  1742: 1,
  2882: 1,
  1685: 1,
  2628: 1,
  193: 1,
  5222: 1,
  3147: 1,
  5187: 1,
  5907: 1,
  89: 1,
  6955: 1,
  705: 1,
  2137: 1,
  3299: 1,
  4787: 1,
  1611: 1,
  2318: 1,
  577: 1,
  2397: 1,
  7268: 1,
  450: 1,
  6884: 1,
  3136: 1,
  71: 1,
  6209: 2,
  1277: 1,
  3620: 1,
  3424: 1,
  438: 1,
  2795: 1,
  6212: 1,
  1221: 1,
  1320: 1,
  6592: 1,
  5415: 1,
  6307: 1,
  3984: 1,
  7171: 1,
  7238: 1,
  404: 1,
  4927: 1,
  5094: 1,
  1601: 1,
  1597: 1,
  3499: 1,
  4065: 1,
  2474: 1,
  3693: 1,
  4466: 1,
  304: 1,
  455: 1,
  2661: 1,
  2888: 1,
  4705: 1,
  939: 1,
  2396: 1,
  1697: 1,
  1504: 1,
  3543: 1,
  3210: 1,
  271: 1,
  3169: 1},
 6945: {6458: 1,
  3540: 1,
  5648: 1,
  5794: 1,
  1689: 1,
  1212: 1,
  5058: 1,
  1304: 1,
  1635: 1,
  4693: 1,
  4096: 1,
  3024: 1,
  5279: 1,
  2669: 1,
  5049: 1,
  5107: 1,
  1902: 1,
  1563: 1,
  6476: 1,
  1388: 1,
  583: 1,
  1707: 1,
  1586: 1,
  151: 1,
  7315: 1,
  1198: 1,
  1284: 1,
  176: 1,
  1079: 1,
  1748: 1,
  7222: 1,
  4252: 1,
  3581: 1,
  868: 1,
  1992: 1,
  6805: 1,
  1598: 1,
  3505: 1,
  5727: 1,
  1232: 1,
  6096: 1,
  5225: 1,
  1611: 1,
  4440: 1,
  4796: 1,
  2836: 1,
  4206: 1,
  2448: 1,
  988: 1,
  1696: 1,
  6263: 1,
  6967: 1,
  1245: 1,
  1848: 1,
  1218: 1,
  6644: 1,
  3060: 1,
  3927: 1,
  5256: 1,
  1469: 1,
  1193: 1,
  5970: 1,
  5671: 1,
  1194: 1,
  4935: 1,
  6238: 1,
  1880: 1,
  3353: 1,
  3455: 1,
  2853: 1,
  1475: 1,
  1164: 1},
 1635: {6458: 1,
  3540: 1,
  5648: 1,
  5794: 2,
  1689: 1,
  1212: 1,
  5058: 1,
  1304: 1,
  6945: 1,
  734: 1,
  5721: 1,
  1328: 1,
  4431: 1,
  1493: 1,
  3504: 1,
  2521: 1,
  1495: 1,
  6120: 1,
  4400: 1,
  4653: 1,
  6777: 1,
  2725: 1,
  1453: 1,
  6914: 1,
  4935: 1,
  5629: 1,
  7022: 1,
  3215: 2,
  2762: 1,
  2433: 1,
  950: 1,
  162: 1,
  1912: 1,
  5199: 1,
  2914: 1,
  4608: 1,
  2889: 1,
  6437: 1,
  5759: 1,
  3875: 1,
  1719: 1,
  4393: 1,
  1346: 1,
  748: 1,
  3556: 1,
  1079: 1,
  7141: 1,
  1080: 1,
  1468: 1,
  1444: 1,
  3338: 1,
  5472: 2,
  7214: 1,
  6843: 1,
  6327: 1,
  1602: 1,
  1722: 1,
  2755: 1,
  1291: 1,
  3325: 1,
  21: 1,
  3309: 1,
  5730: 1,
  539: 1,
  435: 1,
  5734: 1,
  2404: 1,
  1822: 1,
  452: 1,
  6543: 1,
  5504: 1,
  362: 1,
  491: 1,
  8: 1,
  5459: 1,
  2981: 1,
  6881: 1,
  1254: 1,
  3467: 1,
  262: 1,
  1156: 1,
  5833: 1,
  5321: 1,
  3781: 1,
  6142: 1,
  2615: 1,
  6357: 1,
  6051: 1,
  5510: 1,
  4014: 1,
  6727: 1,
  2312: 1,
  5639: 1,
  6651: 1,
  5383: 1,
  1374: 1,
  1520: 1,
  1232: 1,
  2548: 1,
  599: 1,
  1877: 1,
  6071: 1,
  1161: 1,
  1215: 1,
  6249: 1,
  1710: 1,
  6671: 1,
  56: 1,
  4562: 1,
  5539: 1,
  1830: 1,
  1382: 1,
  1810: 1,
  1086: 1,
  2477: 1,
  4760: 1,
  2798: 1,
  1097: 1,
  3307: 1,
  1901: 1,
  2956: 1},
 4439: {6456: 2,
  848: 1,
  1258: 1,
  2535: 1,
  3563: 1,
  1536: 1,
  71: 1,
  2784: 1,
  5381: 1,
  1450: 1,
  3275: 1,
  608: 1,
  2060: 1,
  6198: 1,
  4284: 1,
  3512: 1,
  3898: 1,
  1822: 1,
  1527: 1,
  1123: 1,
  5036: 1,
  6071: 1,
  1394: 1,
  3860: 1,
  208: 1,
  4315: 1,
  1648: 1,
  1776: 1,
  1125: 1,
  5640: 1,
  6864: 1,
  2492: 1,
  1723: 1,
  1820: 1,
  1774: 1,
  1891: 1,
  6500: 1,
  4896: 1,
  6814: 1,
  1814: 1,
  4388: 1,
  1659: 1,
  1461: 1,
  2736: 1,
  5072: 1,
  5487: 1,
  2607: 1,
  2904: 1,
  1430: 1,
  5595: 1,
  4630: 1,
  1899: 1,
  1727: 1,
  707: 1,
  703: 1,
  6606: 1,
  76: 1,
  365: 1,
  1824: 1,
  3837: 1,
  2853: 1,
  3352: 1,
  4701: 1,
  1141: 1,
  465: 1,
  1469: 1,
  1815: 1,
  3992: 2,
  6873: 1,
  2165: 1,
  3522: 1,
  1797: 1,
  5854: 1,
  3015: 1,
  5442: 1,
  6967: 1,
  2341: 1,
  1700: 1,
  6069: 1,
  3840: 1,
  4360: 1,
  10: 1,
  3863: 1,
  4167: 1,
  2185: 1,
  2665: 1,
  5376: 1,
  3694: 1,
  6618: 1,
  2792: 1,
  536: 1,
  2657: 1,
  622: 1,
  315: 1,
  6910: 1,
  5228: 1,
  4356: 1,
  4623: 1,
  4407: 1,
  3570: 1,
  5192: 1,
  1160: 1,
  5766: 1,
  3866: 1,
  2779: 1,
  576: 1,
  1380: 1,
  4331: 1,
  1553: 1,
  1283: 1,
  2873: 1,
  5356: 1,
  3271: 1,
  1092: 1,
  2909: 1,
  5107: 1,
  6190: 1,
  1299: 1,
  1296: 1,
  2321: 1,
  1779: 1,
  3930: 1,
  1957: 1,
  5930: 1,
  3587: 1,
  4756: 1,
  2449: 1,
  6584: 1,
  1819: 1,
  6635: 1,
  6968: 1,
  6497: 1},
 6456: {4439: 2,
  848: 1,
  1258: 1,
  2535: 1,
  3563: 1,
  1536: 1,
  71: 1,
  2784: 1,
  5381: 1,
  1450: 1,
  3275: 1,
  608: 1,
  2060: 1,
  6198: 1,
  4284: 1,
  3512: 1,
  3898: 1,
  2594: 1,
  6595: 1,
  4764: 1,
  1600: 1,
  6006: 1,
  2696: 1,
  5062: 1,
  1012: 1,
  2905: 1,
  1517: 1,
  1311: 1,
  5304: 1,
  1417: 1,
  1768: 1,
  3863: 1,
  5235: 1,
  5705: 1,
  6657: 1,
  1008: 1,
  1323: 1,
  1574: 1,
  6010: 1,
  6581: 1,
  3787: 1,
  6700: 1,
  409: 1,
  2859: 1,
  609: 1,
  2935: 1,
  1678: 1,
  961: 1,
  6548: 1,
  2441: 1,
  3952: 1,
  963: 1,
  1891: 1,
  3772: 1,
  6048: 1,
  6935: 1,
  5472: 1,
  5442: 1,
  1646: 1,
  5810: 1,
  6648: 1,
  6060: 1,
  2988: 1,
  3934: 1,
  1433: 1,
  620: 1,
  7246: 1,
  5832: 1,
  3564: 1,
  274: 1,
  5439: 1,
  924: 1,
  1634: 2,
  1118: 1,
  5948: 1,
  4289: 1,
  5312: 1,
  2515: 1,
  2838: 1,
  4131: 1,
  318: 1,
  6108: 1,
  6934: 1,
  2879: 1,
  6759: 1,
  5901: 1,
  1006: 1,
  5379: 1,
  855: 1,
  5522: 1,
  5064: 1,
  3369: 1,
  4712: 1,
  5926: 1,
  1010: 1,
  1482: 1,
  1753: 1,
  2889: 1,
  1839: 1,
  2809: 1,
  6476: 1,
  174: 1,
  1443: 1,
  4122: 1,
  1884: 1,
  4155: 1,
  1735: 1,
  5495: 1,
  5577: 1,
  5094: 1,
  3851: 1,
  7242: 1,
  109: 1,
  6141: 1,
  5781: 1,
  2865: 1,
  7100: 1,
  2823: 1,
  2981: 1,
  1885: 1,
  1852: 1,
  228: 1,
  4460: 1,
  6542: 1},
 848: {4439: 1,
  6456: 1,
  1258: 1,
  2535: 1,
  3563: 1,
  1536: 1,
  71: 1,
  2784: 1,
  5381: 1,
  696: 1,
  2830: 1,
  1211: 1,
  6846: 1,
  4134: 1,
  1219: 1,
  872: 1,
  900: 1,
  1856: 1,
  1176: 1,
  4147: 1,
  1447: 1,
  4320: 1,
  5646: 1,
  5641: 1,
  5296: 1,
  2318: 1,
  1465: 1,
  1837: 1,
  137: 1,
  1775: 1,
  6650: 1,
  3657: 1,
  6047: 1,
  3628: 1,
  1183: 1,
  4927: 1,
  1504: 1,
  6076: 1,
  546: 1,
  1413: 1,
  1171: 1,
  6482: 1,
  6378: 1,
  6644: 1,
  2469: 1,
  3403: 1,
  4332: 1,
  4660: 1,
  660: 1,
  1582: 1,
  3840: 1,
  7204: 1,
  1521: 1,
  5147: 1,
  3140: 1,
  3582: 1,
  3423: 1,
  5126: 1,
  47: 1,
  4053: 1,
  514: 1,
  4273: 1,
  6592: 1},
 1258: {4439: 1,
  6456: 1,
  848: 1,
  2535: 1,
  3563: 1,
  1536: 1,
  71: 1,
  2784: 1,
  5381: 1,
  6573: 1,
  3040: 1,
  1004: 1,
  6896: 1,
  5961: 2,
  2222: 1,
  5316: 1,
  53: 1,
  7208: 1,
  4963: 1,
  1715: 1,
  3100: 1,
  1175: 1,
  4954: 1,
  7106: 1,
  2628: 1,
  1502: 1,
  1442: 1,
  202: 1,
  4871: 1,
  1949: 1,
  189: 1,
  609: 1,
  4800: 2,
  3278: 2,
  3533: 1,
  6712: 1,
  5475: 1,
  1553: 1,
  3769: 1,
  2582: 1,
  3990: 1,
  3622: 1,
  4833: 1,
  1450: 1,
  2149: 1,
  3227: 1,
  6899: 1,
  782: 1,
  5465: 1,
  3815: 1,
  6273: 1,
  786: 1,
  3222: 1,
  1202: 1,
  747: 1,
  6585: 1,
  4233: 1,
  291: 1,
  4477: 1,
  1784: 1,
  1559: 1,
  1563: 1,
  1507: 1,
  5372: 1,
  4919: 1,
  708: 1,
  48: 1,
  775: 1,
  5373: 1,
  7228: 1,
  1646: 1,
  1570: 1,
  3072: 1,
  2339: 1,
  1738: 1,
  2840: 1,
  1176: 1,
  5131: 1,
  5599: 1,
  1510: 1,
  2482: 1,
  1546: 2,
  744: 1,
  984: 1,
  1717: 1,
  4865: 1,
  6620: 1,
  2956: 1,
  5899: 1,
  1697: 1,
  5522: 1,
  6532: 1,
  2530: 1,
  2217: 1,
  3175: 1,
  1607: 1,
  2380: 1,
  950: 1,
  6558: 1,
  6346: 1,
  4165: 1,
  5622: 1,
  1086: 1,
  4323: 1},
 2535: {4439: 1,
  6456: 1,
  848: 1,
  1258: 1,
  3563: 1,
  1536: 1,
  71: 1,
  2784: 1,
  5381: 1,
  2627: 1,
  5217: 1,
  7301: 1,
  1472: 1,
  7147: 1,
  1429: 1,
  626: 1,
  178: 1,
  1872: 1,
  165: 1,
  3639: 1,
  600: 1,
  6894: 1,
  2210: 1,
  6997: 1,
  1281: 1,
  6852: 1,
  549: 1,
  7006: 1,
  1749: 1,
  4261: 1,
  2975: 1,
  5617: 1,
  3043: 1,
  3352: 1,
  1101: 1,
  1520: 1},
 3563: {4439: 1,
  6456: 1,
  848: 1,
  1258: 1,
  2535: 1,
  1536: 1,
  71: 1,
  2784: 1,
  5381: 1,
  7278: 1,
  1251: 1,
  3954: 1,
  1572: 1,
  3898: 1,
  5376: 1,
  1774: 1,
  1454: 1,
  5071: 1,
  3324: 1,
  1725: 1,
  1504: 2,
  1729: 1,
  1557: 1,
  7064: 1,
  2975: 1,
  1428: 1,
  220: 1,
  754: 1,
  1374: 1,
  1012: 1,
  1639: 1,
  609: 1,
  1122: 1,
  1682: 1,
  1221: 1,
  6504: 1,
  1690: 1,
  1389: 1,
  6109: 1,
  3628: 1,
  1567: 1,
  5998: 1,
  3493: 1,
  5047: 1,
  4969: 1,
  1898: 1,
  1385: 1,
  6465: 1,
  731: 1,
  4671: 1,
  4675: 1,
  3928: 1,
  2436: 1,
  1549: 1,
  6433: 1,
  1233: 1,
  3787: 1,
  6485: 1,
  5619: 1,
  1901: 1,
  6814: 1,
  1225: 1,
  1400: 1,
  1476: 1,
  3770: 1,
  1126: 1,
  49: 1,
  6346: 1,
  5222: 1,
  4756: 2,
  3671: 1,
  1722: 1,
  6071: 1,
  5447: 1,
  4924: 1,
  2671: 1,
  2562: 1,
  3460: 1,
  3017: 1,
  7237: 1,
  318: 1,
  4408: 1,
  2840: 1,
  4289: 1,
  4374: 1,
  7263: 1,
  841: 1,
  4804: 1,
  1370: 1,
  778: 1,
  2810: 1,
  2739: 1,
  7316: 1,
  470: 1,
  3297: 1,
  5160: 1,
  5183: 1,
  764: 1,
  1551: 1,
  2356: 1,
  7103: 1,
  5972: 1,
  6447: 1,
  569: 1,
  1830: 1},
 1536: {4439: 1,
  6456: 1,
  848: 1,
  1258: 1,
  2535: 1,
  3563: 1,
  71: 1,
  2784: 1,
  5381: 1,
  1813: 1,
  6198: 1,
  1792: 1,
  3489: 1,
  5338: 1,
  2888: 1,
  6726: 1,
  1203: 1,
  1365: 1,
  1225: 1,
  3920: 1,
  4794: 1,
  4071: 1,
  5914: 1,
  2641: 1,
  1362: 1,
  1094: 1,
  1052: 1,
  6384: 1,
  3597: 1,
  1210: 1,
  727: 1,
  1342: 1,
  1815: 1,
  2671: 1,
  3418: 1,
  2595: 1,
  5375: 1,
  1601: 1,
  4438: 1,
  376: 1,
  1789: 1,
  3309: 1,
  1904: 1,
  4319: 1,
  2548: 1,
  1607: 1,
  385: 1,
  599: 1,
  6032: 1,
  1993: 1,
  5151: 1,
  3096: 1,
  2229: 1,
  7125: 1,
  1452: 1,
  5878: 1,
  2951: 1,
  2469: 1,
  2810: 1,
  1894: 1,
  1837: 1,
  6742: 1,
  4214: 1,
  3324: 1,
  5029: 1,
  6912: 1,
  4182: 1,
  6005: 1,
  3571: 1,
  2893: 1,
  1614: 1,
  2262: 1,
  66: 1,
  1868: 1,
  6165: 1,
  3958: 1,
  4139: 2,
  5697: 1,
  794: 1,
  1344: 1,
  1270: 1,
  471: 1,
  970: 1,
  2657: 1,
  3731: 1,
  3729: 1,
  3957: 1,
  2380: 1,
  3912: 1,
  6565: 1,
  4428: 1,
  3258: 1,
  1719: 1,
  5365: 1,
  1803: 1,
  3358: 1,
  1490: 1,
  2850: 1,
  1743: 1,
  4272: 1,
  1784: 1,
  6309: 1,
  1687: 1,
  3488: 1,
  4400: 1,
  6413: 1,
  2811: 1,
  1443: 1,
  1159: 1,
  3799: 1,
  3453: 1,
  127: 1,
  3775: 1,
  1473: 1,
  5164: 1,
  2584: 1,
  4823: 1,
  3490: 1,
  5071: 1,
  1576: 1,
  4616: 1,
  2560: 1,
  5483: 1,
  1356: 1,
  30: 1,
  3401: 1,
  2403: 1,
  4167: 1,
  3787: 1,
  1666: 1,
  6433: 1,
  2743: 1,
  4598: 1,
  7239: 1,
  2675: 1,
  2861: 1,
  4724: 1,
  7107: 1,
  6024: 1,
  1491: 1,
  1774: 1,
  1814: 1,
  6872: 1,
  5063: 1,
  1368: 1,
  1836: 1,
  7159: 1,
  4873: 1,
  3086: 1,
  6206: 1,
  5955: 1,
  1734: 1},
 71: {4439: 1,
  6456: 1,
  848: 1,
  1258: 1,
  2535: 1,
  3563: 1,
  1536: 1,
  2784: 1,
  5381: 1,
  3025: 1,
  1147: 1,
  1427: 1,
  1235: 1,
  4779: 1,
  5199: 1,
  2414: 1,
  3390: 1,
  1402: 1,
  655: 1,
  2502: 1,
  3852: 1,
  4734: 1,
  4717: 1,
  1437: 1,
  3833: 1,
  2634: 1,
  5085: 1,
  992: 1,
  3083: 1,
  1761: 1,
  2607: 1,
  7171: 1,
  293: 1,
  2400: 1,
  5325: 1,
  6415: 1,
  1585: 1,
  1891: 1,
  1064: 1,
  1382: 1,
  5: 1,
  7128: 1,
  897: 1,
  1135: 1,
  2512: 1,
  7268: 1,
  1304: 1,
  450: 1,
  6884: 1,
  3136: 1,
  6209: 1,
  1277: 1,
  3620: 1,
  3424: 1,
  6773: 1,
  2543: 1,
  2965: 1,
  1266: 1,
  1606: 1,
  5355: 1,
  1107: 1,
  6851: 1,
  4703: 1,
  2161: 1,
  6941: 1,
  7239: 1,
  4594: 1,
  627: 1,
  2867: 1,
  6842: 1,
  3553: 1,
  139: 1},
 2784: {4439: 1,
  6456: 1,
  848: 1,
  1258: 1,
  2535: 1,
  3563: 1,
  1536: 1,
  71: 1,
  5381: 1,
  2732: 1,
  4708: 1,
  4101: 1,
  5070: 1,
  2298: 1,
  2679: 1,
  1156: 1,
  2881: 1,
  3209: 1,
  294: 1,
  5272: 1,
  7067: 1,

# Обработка датасета

In [ ]:
df = feed.merge(user, on='user_id', how='left')
df = df.merge(post, on='post_id', how='left')

df

,timestamp,user_id,post_id,action,target,gender,age,country,city,exp_group,os,source,text,topic
0,2021-10-23 11:42:31,30988,220,view,0,1,48,Russia,Yekaterinburg,1,Android,ads,Deutsche attacks Yukos case\n\nGerman investme...,business
1,2021-10-23 11:44:36,30988,5805,view,0,1,48,Russia,Yekaterinburg,1,Android,ads,Critics have started calling it the Oscar Winn...,movie
2,2021-10-23 11:46:38,30988,650,view,0,1,48,Russia,Yekaterinburg,1,Android,ads,Holmes wins 2004 top TV moment\n\nSprinter Kel...,entertainment
3,2021-10-23 11:48:02,30988,2442,view,1,1,48,Russia,Yekaterinburg,1,Android,ads,@MikeEspyMS Mississippi has the highest per ca...,covid
4,2021-10-23 11:50:50,30988,2442,like,0,1,48,Russia,Yekaterinburg,1,Android,ads,@MikeEspyMS Mississippi has the highest per ca...,covid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999995,2021-11-03 20:03:56,82298,2374,view,0,0,37,Russia,Penza,3,iOS,ads,@greggutfeld Portland is happening on Dear Lea...,covid
1999996,2021-11-03 20:06:35,82298,6134,view,0,0,37,Russia,Penza,3,iOS,ads,This is the first time I have commented on a f...,movie
1999997,2021-11-12 14:24:16,82298,6181,view,0,0,37,Russia,Penza,3,iOS,ads,That is the best way I can describe this movie...,movie
1999998,2021-11-12 14:24:34,82298,1470,view,0,0,37,Russia,Penza,3,iOS,ads,Ronaldo considering new contract\n\nManchester...,sport
1999999,2021-11-12 14:25:55,82298,3393,view,0,0,37,Russia,Penza,3,iOS,ads,"📦🍎🍞Drive-Thru #Free #FoodGiveaway August 14, 9...",covid

In [ ]:
df = df[df['action'] == 'view']
df = df.drop('action', axis = 1)

df = df.drop('text', axis = 1)
df = df.drop('source', axis=1)

In [ ]:
user_likes_dict = user_likes.to_dict()

def get_item_based_score(user_id, target_post_id):
  if user_id not in user_likes_dict or target_post_id not in item_item_sim:
    return 0

  past_likes = user_likes_dict[user_id]
  score = 0
  sim_posts = item_item_sim[target_post_id]

  for past_post in past_likes:
    if past_post in sim_posts:
      score += sim_posts[past_post]

  return score

In [ ]:
df['item_similarity_score'] = df.apply(
    lambda x:get_item_based_score(x['user_id'], x['post_id']), axis = 1
    )

In [ ]:
df['month'] = df['timestamp'].dt.month
df['hour'] = df['timestamp'].dt.hour

df = df.sort_values('timestamp')
df = df.drop('timestamp', axis =1)

df = df.drop(['user_id', 'post_id'], axis = 1)
df

,target,gender,age,country,city,exp_group,os,topic,item_similarity_score,month,hour
1558725,0,1,28,Russia,Moscow,0,Android,movie,0,10,6
1721752,0,1,27,Ukraine,Vremivka,2,Android,movie,5,10,6
1558726,0,1,28,Russia,Moscow,0,Android,tech,0,10,6
1721753,0,1,27,Ukraine,Vremivka,2,Android,entertainment,2,10,6
386649,1,0,19,Russia,Stavropol,1,iOS,movie,1,10,6
...,...,...,...,...,...,...,...,...,...,...,...
691450,1,1,37,Russia,Shakhty,1,iOS,covid,9,12,23
850382,1,1,46,Russia,Moscow,0,iOS,covid,9,12,23
850384,1,1,46,Russia,Moscow,0,iOS,movie,9,12,23
1656207,1,0,20,Turkey,Bucak,4,iOS,movie,9,12,23
691452,1,1,37,Russia,Shakhty,1,iOS,movie,9,12,23

In [ ]:
board = int(df.shape[0]*0.8)
train = df.iloc[:board].copy()
test = df.iloc[board:].copy()

train_X = train.drop('target', axis = 1)
train_y = train['target']

test_X = test.drop('target', axis = 1)
test_y = test['target']

# Обучение CatBoost

In [ ]:
def load_models():
    model = CatBoostClassifier()
    model_path = '/content/catboost_model_5'

    model.load_model(model_path)

    return model

In [ ]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.8)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.2)

In [ ]:
from catboost import CatBoostClassifier

In [ ]:
train_columns = [
    'gender', 'age', 'country', 'city', 'exp_group', 'os',
    'topic', 'item_similarity_score', 'month', 'hour'
]

test_X_sorted = test_X[train_columns].copy()

model = load_models()
val_df = test_X.copy()
val_df['target'] = test_y.copy()
val_df['user_id'] = df['user_id']

val_df['predict_proba'] = model.predict_proba(test_X_sorted)[:, 1]
val_df.sort_values(['user_id', 'predict_proba'], ascending=[True, False], inplace=True)

top_5_recs = val_df.groupby('user_id').head(5)

hit_rate = top_5_recs.groupby('user_id')['target'].max().mean()

print(f"HitRate@5: {hit_rate:.4f}")

HitRate@5: 0.9868

In [ ]:
cat_cols = df.select_dtypes(include = object).columns
cat_cols

Index(['country', 'city', 'os', 'topic'], dtype='object')

In [ ]:
model = CatBoostClassifier(
    cat_features = cat_cols.tolist(),
    eval_metric='AUC',
    verbose = 100
)

model.fit(train_X, train_y)

Learning rate set to 0.229258
0:	total: 2.06s	remaining: 34m 16s
100:	total: 2m 32s	remaining: 22m 39s
200:	total: 5m 4s	remaining: 20m 11s
300:	total: 7m 36s	remaining: 17m 39s
400:	total: 10m 10s	remaining: 15m 11s
500:	total: 12m 41s	remaining: 12m 38s
600:	total: 15m 17s	remaining: 10m 9s
700:	total: 17m 48s	remaining: 7m 35s
800:	total: 20m 21s	remaining: 5m 3s
900:	total: 22m 57s	remaining: 2m 31s
999:	total: 25m 33s	remaining: 0us

In [ ]:
from sklearn.metrics import roc_auc_score

preds = model.predict_proba(test_X)[:, 1]

auc = roc_auc_score(test_y, preds)

model.save_model('catboost_model_5', format = 'cbm')

In [ ]:
auc = roc_auc_score(test_y, preds)
auc

np.float64(0.9060331747715176)

# Выгрузка артефактов

In [ ]:
# user_table = pd.read_sql(f'SELECT * FROM {TABLE_USERS_SAVE}', con=engine)
# user_table.to_sql(f'{TABLE_USERS_SAVE}', con=engine, if_exists='replace')

user.to_sql(TABLE_USERS_SAVE, con=engine, if_exists='replace', index=False)

In [ ]:
# post_table = pd.read_sql(f'SELECT * FROM {TABLE_POSTS_SAVE}', con=engine)
# post_table.to_sql(f'{TABLE_POSTS_SAVE}', con=engine, if_exists='replace')

In [ ]:
user.to_sql(TABLE_USERS_SAVE, con=engine, if_exists='replace', index=False)
post.to_sql(TABLE_POSTS_SAVE, con=engine, if_exists='replace', index=False)

23

In [ ]:
post

,post_id,topic,text_pca_0,text_pca_1,text_pca_2,text_pca_3,text_pca_4,text_pca_5,text_pca_6,text_pca_7,text_pca_8,text_pca_9,text_pca_10,text_pca_11,text_pca_12,text_pca_13,text_pca_14
0,1,business,-1.912991,2.691439,1.915973,-0.422896,-0.345944,-0.141953,-0.519414,0.269280,-0.779597,0.095312,-0.277381,0.991838,0.585162,-0.644162,0.001618
1,2,business,-1.727319,2.029549,0.429522,-0.294997,-0.560949,0.328649,0.318612,0.104411,0.526693,0.453533,-0.832914,0.212289,0.026044,0.332391,0.141258
2,3,business,-1.474857,1.489152,1.876078,-1.394238,0.295947,-0.111797,-0.809332,-0.011606,0.166902,0.250074,-0.115336,-0.230905,0.579137,-0.112857,-0.077984
3,4,business,-1.630674,1.246256,1.526981,-1.003090,0.004563,-0.368847,0.011742,-1.050481,-0.101742,0.402329,-0.592706,-0.306064,1.053104,0.080389,-0.444724
4,5,business,-1.105120,1.515799,1.474110,-1.008102,0.685202,-0.560234,0.166204,-0.367064,0.331827,0.302498,1.069357,-0.443248,0.458108,-0.131247,0.554725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7315,movie,1.640787,-0.124328,0.081669,0.903768,0.839771,-0.729611,-0.696651,0.184448,0.758011,0.243383,0.276293,0.321754,0.138325,-0.130263,-0.171082
7019,7316,movie,1.566288,-0.483328,0.064193,1.036240,0.807080,-0.680928,-0.632896,-0.340440,0.150495,-0.262555,0.415595,0.269728,0.255220,0.253661,0.133110
7020,7317,movie,1.764852,-0.488970,0.525260,1.104395,1.022655,-0.216204,-0.680050,0.037205,0.686270,-0.118566,0.231532,-0.077620,-0.043853,-0.191846,0.216526
7021,7318,movie,2.128935,-0.236707,-0.115322,-0.625785,-0.350396,0.093832,-0.145748,-0.325237,0.201284,0.091278,-0.311712,0.121449,0.507502,0.028515,0.099402
7022,7319,movie,1.797203,-0.689242,0.461329,-0.663797,-0.074445,1.268649,0.179540,0.201428,-0.469788,0.440805,-0.216331,0.108373,-0.454074,0.278065,0.391160

In [ ]:
df_pca = pd.read_sql(f'SELECT * FROM {TABLE_POSTS_SAVE}', con=engine)

df_text = pd.read_sql(f'SELECT * FROM {TABLE_POSTS}', con=engine)

final_df = df_pca.merge(df_text[['post_id', 'text']], on='post_id', how='left')

final_df.to_sql(TABLE_POSTS_SAVE, con=engine, if_exists='replace', index=False)

23

In [ ]:
df_text

      post_id                                               text     topic
0           1  UK economy facing major risks\n\nThe UK manufa...  business
1           2  Aids and climate top Davos agenda\n\nClimate c...  business
2           3  Asian quake hits European shares\n\nShares in ...  business
3           4  India power shares jump on debut\n\nShares in ...  business
4           5  Lacroix label bought by US firm\n\nLuxury good...  business
...       ...                                                ...       ...
7018     7315  OK, I would not normally watch a Farrelly brot...     movie
7019     7316  I give this movie 2 stars purely because of it...     movie
7020     7317  I cant believe this film was allowed to be mad...     movie
7021     7318  The version I saw of this film was the Blockbu...     movie
7022     7319  Piece of subtle art. Maybe a masterpiece. Doub...     movie

[7023 rows x 3 columns]

In [ ]:
score_data = []
for post_id, neigh in item_item_sim.items():
  for neigh_id, score in neigh.items():
    score_data.append({'post_id': post_id, 'neighbor_id': neigh_id, 'score': score})

score_df = pd.DataFrame(score_data)
score_df.to_sql(f'{TABLE_SCORE_SAVE}', con=engine,if_exists='replace')

31

In [ ]:
likes_df = pd.read_sql(f"SELECT user_id, post_id FROM {TABLE_FEED} WHERE action='like' LIMIT 2000000", con=engine)
likes_df.to_sql(
    f'{TABLE_LIKES_SAVE}',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=5000,
    method='multi'
)

2000000

# Add NN

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModel
import numpy as np

In [ ]:
model_name = 'distilbert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
@torch.inference_mode()
def get_embedding(text, model,tokenizer):
  t = tokenizer(text, padding=True, truncation=True, return_tensors='pt')
  output = model(**t)

  return output.last_hidden_state[:,0,:].numpy()[0]

In [ ]:
from tqdm import tqdm
tqdm.pandas()

post['embeddings'] = post['text'].progress_apply(lambda x: get_embedding(x, model, tokenizer))

100%|██████████| 7023/7023 [53:36<00:00,  2.18it/s]

In [ ]:
from sklearn.decomposition import PCA

embeddings_matrix = np.stack(post['embeddings'].values)

n_comp = 15
pca = PCA(n_components = n_comp)
pca_embeddings = pca.fit_transform(embeddings_matrix)

for i in range(n_comp):
  post[f'text_pca_{i}'] = pca_embeddings[:,i]

post = post.drop(['embeddings', 'text'], axis = 1)

post.to_pickle('posts_with_pca.pkl')
post

,post_id,topic,text_pca_0,text_pca_1,text_pca_2,text_pca_3,text_pca_4,text_pca_5,text_pca_6,text_pca_7,text_pca_8,text_pca_9,text_pca_10,text_pca_11,text_pca_12,text_pca_13,text_pca_14
0,1,business,-1.912991,2.691439,1.915973,-0.422896,-0.345944,-0.141953,-0.519414,0.269280,-0.779597,0.095312,-0.277381,0.991838,0.585162,-0.644162,0.001618
1,2,business,-1.727319,2.029549,0.429522,-0.294997,-0.560949,0.328649,0.318612,0.104411,0.526693,0.453533,-0.832914,0.212289,0.026044,0.332391,0.141258
2,3,business,-1.474857,1.489152,1.876078,-1.394238,0.295947,-0.111797,-0.809332,-0.011606,0.166902,0.250074,-0.115336,-0.230905,0.579137,-0.112857,-0.077984
3,4,business,-1.630674,1.246256,1.526981,-1.003090,0.004563,-0.368847,0.011742,-1.050481,-0.101742,0.402329,-0.592706,-0.306064,1.053104,0.080389,-0.444724
4,5,business,-1.105120,1.515799,1.474110,-1.008102,0.685202,-0.560234,0.166204,-0.367064,0.331827,0.302498,1.069357,-0.443248,0.458108,-0.131247,0.554725
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7315,movie,1.640787,-0.124328,0.081669,0.903768,0.839771,-0.729611,-0.696651,0.184448,0.758011,0.243383,0.276293,0.321754,0.138325,-0.130263,-0.171082
7019,7316,movie,1.566288,-0.483328,0.064193,1.036240,0.807080,-0.680928,-0.632896,-0.340440,0.150495,-0.262555,0.415595,0.269728,0.255220,0.253661,0.133110
7020,7317,movie,1.764852,-0.488970,0.525260,1.104395,1.022655,-0.216204,-0.680050,0.037205,0.686270,-0.118566,0.231532,-0.077620,-0.043853,-0.191846,0.216526
7021,7318,movie,2.128935,-0.236707,-0.115322,-0.625785,-0.350396,0.093832,-0.145748,-0.325237,0.201284,0.091278,-0.311712,0.121449,0.507502,0.028515,0.099402
7022,7319,movie,1.797203,-0.689242,0.461329,-0.663797,-0.074445,1.268649,0.179540,0.201428,-0.469788,0.440805,-0.216331,0.108373,-0.454074,0.278065,0.391160

In [ ]:
print("Колонки в post:", [c for c in post.columns if 'text_pca' in c])

Колонки в post: ['text_pca_0', 'text_pca_1', 'text_pca_2', 'text_pca_3', 'text_pca_4', 'text_pca_5', 'text_pca_6', 'text_pca_7', 'text_pca_8', 'text_pca_9', 'text_pca_10', 'text_pca_11', 'text_pca_12', 'text_pca_13', 'text_pca_14']

In [ ]:
post = pd.read_pickle('posts_with_pca.pkl')

In [ ]:
df = feed[feed['action'] == 'view'].copy()
df = df.merge(user, on='user_id', how='left')
df = df.merge(post, on='post_id', how='left')
df.columns

Index(['timestamp', 'user_id', 'post_id', 'action', 'target', 'gender', 'age',
       'country', 'city', 'exp_group', 'os', 'source', 'topic', 'text_pca_0',
       'text_pca_1', 'text_pca_2', 'text_pca_3', 'text_pca_4', 'text_pca_5',
       'text_pca_6', 'text_pca_7', 'text_pca_8', 'text_pca_9', 'text_pca_10',
       'text_pca_11', 'text_pca_12', 'text_pca_13', 'text_pca_14'],
      dtype='object')

In [ ]:
df['month'] = df['timestamp'].dt.month
df['hour'] = df['timestamp'].dt.hour
df['item_similarity_score'] = df.apply(
    lambda x: get_item_based_score(x['user_id'], x['post_id']), axis=1
)

In [ ]:
df = df.sort_values('timestamp')

In [ ]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.3)
Downloading catboost-1.2.8-cp312-cp312-manylinux2014_x86_64.whl (99.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 14.2 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.8

In [ ]:
from catboost import CatBoostClassifier

In [ ]:
pca_columns = [f'text_pca_{i}' for i in range(n_comp)]

train_columns = ['gender', 'age', 'country', 'city', 'exp_group', 'os',
    'topic', 'item_similarity_score', 'month', 'hour'] + pca_columns

cat_cols = [
    'gender', 'country', 'city', 'exp_group', 'os', 'topic',
    'month', 'hour' # Месяц и час тоже лучше пометить как категориальные
]

split_index = int(df.shape[0] * 0.8)

train_df = df.iloc[:split_index].copy()
test_df = df.iloc[split_index:].copy()

X_train = train_df[train_columns]
y_train = train_df['target']

X_test = test_df[train_columns]
y_test = test_df['target']


model_cat = CatBoostClassifier(
    cat_features=cat_cols,
    eval_metric='AUC',
    verbose=100
)

model_cat.fit(X_train, y_train, eval_set = (X_test, y_test))

Learning rate set to 0.190629
0:	test: 0.8423038	best: 0.8423038 (0)	total: 2.18s	remaining: 36m 18s
100:	test: 0.9030661	best: 0.9030661 (100)	total: 4m 20s	remaining: 38m 36s
200:	test: 0.9039132	best: 0.9039132 (200)	total: 8m 44s	remaining: 34m 46s
300:	test: 0.9043786	best: 0.9043786 (300)	total: 13m 11s	remaining: 30m 37s
400:	test: 0.9044996	best: 0.9045103 (397)	total: 17m 37s	remaining: 26m 19s
500:	test: 0.9047162	best: 0.9047317 (496)	total: 22m 9s	remaining: 22m 4s
600:	test: 0.9046979	best: 0.9047396 (538)	total: 26m 39s	remaining: 17m 41s
700:	test: 0.9047082	best: 0.9047396 (538)	total: 31m 13s	remaining: 13m 19s
800:	test: 0.9046806	best: 0.9047396 (538)	total: 35m 43s	remaining: 8m 52s
900:	test: 0.9046329	best: 0.9047396 (538)	total: 40m 11s	remaining: 4m 25s
999:	test: 0.9046707	best: 0.9047396 (538)	total: 44m 41s	remaining: 0us

bestTest = 0.904739628
bestIteration = 538

Shrink model to first 539 iterations.

In [ ]:
test_df['predict_proba'] = model_cat.predict_proba(X_test)[:, 1]
test_df.sort_values(['user_id', 'predict_proba'], ascending=[True, False], inplace=True)

top_5_recs = test_df.groupby('user_id').head(5)
hit_rate = top_5_recs.groupby('user_id')['target'].max().mean()

print(f"HitRate@5: {hit_rate:.4f}")

if hit_rate > 0.57:
    print("Сохраняем модель...")
    model_cat.save_model('catboost_model_6.cbm')
else:
    print("Соси")

HitRate@5: 0.9885
Сохраняем модель...

# A/B Test

In [4]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [5]:
likes = pd.read_csv('likes.csv')
views = pd.read_csv('views.csv')

In [6]:
likes

        user_id  post_id   timestamp
0        128381     4704  1654030804
1        146885     1399  1654030816
2         50948     2315  1654030828
3         14661      673  1654030831
4         37703     1588  1654030833
...         ...      ...         ...
230171    31851     5964  1655243535
230172    51512     1498  1655243537
230173    34017     5009  1655243573
230174    13267     1787  1655243692
230175    67302     7255  1655243736

[230176 rows x 3 columns]

In [7]:
views

        user_id exp_group             recommendations   timestamp
0        128381   control  [3644 4529 4704 5294 4808]  1654030803
1        146885      test  [1399 1076  797 7015 5942]  1654030811
2         50948      test  [2315 3037 1861 6567 4093]  1654030825
3         37703      test  [2842 1949  162 1588 6794]  1654030826
4         14661      test  [2395 5881 5648 3417  673]  1654030829
...         ...       ...                         ...         ...
193290   158267      test  [1733 6834 4380 1915 1627]  1655240340
193291    63527   control  [2454  191 3873 6404 1588]  1655240347
193292    52169      test  [1368 1709 1616  798 5305]  1655240354
193293   142402      test  [5895 6984 1978 6548 6106]  1655240373
193294    72259   control  [6117 1255 6567 3587 3811]  1655240388

[193295 rows x 4 columns]

In [9]:
duplic = views.groupby('user_id')['exp_group'].nunique()
duplic

user_id
200       1
201       1
202       1
212       1
213       1
         ..
168538    1
168541    1
168544    1
168545    1
168552    1
Name: exp_group, Length: 65013, dtype: int64

In [11]:
more_then_2 = duplic[duplic > 1].index.tolist()
more_then_2

[25623, 55788, 142283, 148670]

In [13]:
if len(more_then_2) > 0:
  views_clear = views[~views['user_id'].isin(more_then_2)]
  likes_clear = likes[~likes['user_id'].isin(more_then_2)]

In [16]:
user_group = views_clear[['user_id', 'exp_group']].drop_duplicates()
user_group

        user_id exp_group
0        128381   control
1        146885      test
2         50948      test
3         37703      test
4         14661      test
...         ...       ...
193267    80500      test
193270   149686      test
193285     3615   control
193288   119630      test
193293   142402      test

[65009 rows x 2 columns]

In [19]:
group_sizes = user_group['exp_group'].value_counts()
print(f'Group sizes: {group_sizes}')

n_control = group_sizes.get('control', 0)
n_test = group_sizes.get('test', 0)
n_total = n_control+n_test

print(f"Доля контрольной группы: {n_control / n_total:.4f}")

Group sizes: exp_group
test       32659
control    32350
Name: count, dtype: int64
Доля контрольной группы: 0.4976

In [21]:
test_result = st.binomtest(k=n_control, n=n_total, p = 0.5, alternative='two-sided')
print(f"P-value биномиального теста: {test_result.pvalue:.4f}")

if test_result.pvalue < 0.05:
    print("ВНИМАНИЕ: Разбиение статистически значимо отличается от 50/50 (система сплитования работает криво).")
else:
    print("УСПЕХ: Отклонения в размерах групп случайны, разбиение 50/50 работает корректно.")

P-value биномиального теста: 0.2271
УСПЕХ: Отклонения в размерах групп случайны, разбиение 50/50 работает корректно.

In [22]:
experiment_users = pd.DataFrame({'user_id': views_clear['user_id'].unique()})

likes_per_user = likes_clear.groupby('user_id').size().reset_index(name = 'likes_count')

user_metrics = experiment_users.merge(likes_per_user, on='user_id', how='left')
user_metrics['likes_count'] = user_metrics['likes_count'].fillna(0)

user_metrics.head(5)

   user_id  likes_count
0   128381          7.0
1   146885          4.0
2    50948          5.0
3    37703          6.0
4    14661         11.0

In [23]:
user_metrics['has_liked'] = (user_metrics['likes_count']>0).astype(int)
overall_conversion = user_metrics['has_liked'].mean()

print(f"\nДоля пользователей, сделавших хотя бы 1 лайк: {overall_conversion:.4f} "
      f"({overall_conversion * 100:.2f}%)")

Доля пользователей, сделавших хотя бы 1 лайк: 0.8948 (89.48%)

In [24]:
from statsmodels.stats.proportion import proportions_ztest

df_ab = user_metrics.merge(user_group, on='user_id', how='inner')
group_a = df_ab[df_ab['exp_group'] == 'control']
group_b = df_ab[df_ab['exp_group'] == 'test']

Тест 1: Z-критерий для долей (Конверсия)

In [25]:
successes = [group_a['has_liked'].sum(), group_b['has_liked'].sum()]
nobs =[len(group_a), len(group_b)]

stat_z, pval_z = proportions_ztest(successes, nobs)

print(f"Конверсия Control: {group_a['has_liked'].mean():.4f}")
print(f"Конверсия Test:    {group_b['has_liked'].mean():.4f}")
print(f"Z-test p-value:    {pval_z:.4f}")

Конверсия Control: 0.8913
Конверсия Test:    0.8982
Z-test p-value:    0.0045

Тест 2: Критерий Манна-Уитни (Число лайков)

In [27]:
stat_mw, pval_mw = st.mannwhitneyu(group_a['likes_count'], group_b['likes_count'], alternative='two-sided')

print(f"\nСреднее число лайков Control: {group_a['likes_count'].mean():.4f}")
print(f"Среднее число лайков Test:    {group_b['likes_count'].mean():.4f}")
print(f"Mann-Whitney p-value:         {pval_mw:.4f}")

Среднее число лайков Control: 3.4871
Среднее число лайков Test:    3.5926
Mann-Whitney p-value:         0.0000

## hitrate

In [28]:
import re

def parse_recs(val):
    if isinstance(val, str):
        return[int(x) for x in re.findall(r'\d+', val)]
    return val

views['recommendations'] = views['recommendations'].apply(parse_recs)
original_views_count = views.shape[0]

In [29]:
views_exploded = views.explode('recommendations').rename(columns={'recommendations': 'post_id'})

views_exploded = views_exploded.rename(columns={'timestamp': 'timestamp_view'})
likes = likes.rename(columns={'timestamp': 'timestamp_like'})

In [30]:
merged = views_exploded.merge(likes, on=['user_id', 'post_id'], how='left')

In [31]:
time_diff = merged['timestamp_like'] - merged['timestamp_view']

cond_valid = (time_diff >= 0) & (time_diff <= 3600)

merged['is_valid_like'] = cond_valid.astype(int)

In [32]:
hitrate_df = merged.groupby(['user_id', 'timestamp_view', 'exp_group'])['is_valid_like'].max().reset_index()

print(f"Исходно показов: {original_views_count}")
print(f"После обработки: {hitrate_df.shape[0]} (должно совпадать!)")

Исходно показов: 193295
После обработки: 193295 (должно совпадать!)

In [33]:
overall_hitrate = hitrate_df['is_valid_like'].mean()
print(f"\nОбщий HitRate: {overall_hitrate:.4f} ({overall_hitrate * 100:.2f}%)")

hitrate_by_group = hitrate_df.groupby('exp_group')['is_valid_like'].mean()
print("\nHitRate по группам:")
print(hitrate_by_group)

Общий HitRate: 0.7133 (71.33%)

HitRate по группам:
exp_group
control    0.706655
test       0.719843
Name: is_valid_like, dtype: float64

# Бакетный подход

In [35]:
import hashlib

def get_bucket(user_id, num_buckets=100):
    return int(hashlib.md5(str(user_id).encode()).hexdigest(), 16) % num_buckets

hitrate_df['bucket'] = hitrate_df['user_id'].apply(get_bucket)

bucket_metrics = hitrate_df.groupby(['exp_group', 'bucket']).agg(
    hits=('is_valid_like', 'sum'),
    shows=('is_valid_like', 'count')
).reset_index()

bucket_metrics['bucket_hitrate'] = bucket_metrics['hits'] / bucket_metrics['shows']

control_buckets = bucket_metrics[bucket_metrics['exp_group'] == 'control']['bucket_hitrate']
test_buckets = bucket_metrics[bucket_metrics['exp_group'] == 'test']['bucket_hitrate']


print(f"Средний HitRate по бакетам Control: {control_buckets.mean():.4f}")
print(f"Средний HitRate по бакетам Test:    {test_buckets.mean():.4f}")

stat_t, pval_t = st.ttest_ind(control_buckets, test_buckets, equal_var=False)

stat_mw, pval_mw = st.mannwhitneyu(control_buckets, test_buckets, alternative='two-sided')

print(f"\nT-test p-value:         {pval_t:.6f}")
print(f"Mann-Whitney p-value:   {pval_mw:.6f}")

Средний HitRate по бакетам Control: 0.7065
Средний HitRate по бакетам Test:    0.7199

T-test p-value:         0.000000
Mann-Whitney p-value:   0.000000